#pragma once

// 主题值与宏名保持一致，避免跨模块使用隐式字符串。
#define QFRAMEWORK_IMAGE_RAW "QFRAMEWORK_IMAGE_RAW"
#define QFRAMEWORK_IMAGE_PROCESSED "QFRAMEWORK_IMAGE_PROCESSED"
#define QFRAMEWORK_LOG_DISPLAY "QFRAMEWORK_LOG_DISPLAY"
#define QFRAMEWORK_STATUS "QFRAMEWORK_STATUS"
